trigger:
- master

jobs:

- job: Pipeline
  strategy:
    matrix:
      linux:
        python.version: '3.7'
        imageName: 'ubuntu-16.04'
      windows:
        python.version: '3.7'
        imageName: 'vs2017-win2016'
    maxParallel: 4

  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
    displayName: 'PyPI Cache Restore'
    inputs:
      # TODO: Python version for each artifact?
      keyfile: 'poetry.lock'
      targetfolder: '.venv, .poetry'
      vstsFeed: '$(CacheArtifactFeedId)'

    # venv is idempotent - no issues if cache has been restored
  - script: python -m venv .poetry
    displayName: Make Poetry venv

  - task: PythonScript@0
    displayName: Setup Poetry 1
    inputs:
      scriptPath: .ci/scripts/python.py
      arguments: -m pip install --upgrade pip
    env:
      VENV: .poetry

  - task: PythonScript@0
    displayName: Setup Poetry 2
    inputs:
      scriptPath: .ci/scripts/python.py
      arguments: -m pip install --upgrade poetry
    env:
      VENV: .poetry

  - task: PythonScript@0
    displayName: Configure Poetry 1
    inputs:
      scriptPath: .ci/scripts/python.py
      arguments: -m poetry config settings.virtualenvs.in-project true
    env:
      VENV: .poetry

  - task: PythonScript@0
    displayName: Configure Poetry 2
    inputs:
      scriptPath: .ci/scripts/python.py
      arguments: -m poetry config settings.virtualenvs.path .venv
    env:
      VENV: .poetry

    # Letting Python install the virtual environment works around an issue
    # seen where ensurepip fails when poetry executes the installation.
  - script: python -m venv .venv
    displayName: Make app venv

  - task: PythonScript@0
    displayName: Install/update dependencies
    inputs:
      scriptPath: .ci/scripts/python.py
      arguments: -m poetry install
    env:
      VENV: .poetry

    # If dependency resolution succeeded, cache.
  - task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
    displayName: 'PyPI Cache Save'
    inputs:
      keyfile: 'poetry.lock'
      targetfolder: '.venv, .poetry'
      vstsFeed: '$(CacheArtifactFeedId)'

  - task: PublishPipelineArtifact@0
    displayName: Debug
    inputs:
      artifactName: 'debug_$(python.version)_$(Agent.OS)'
      targetPath: strace.poetry.log
    condition: succeededOrFailed()

  - task: PythonScript@0
    displayName: Test
    inputs:
      scriptPath: .ci/scripts/python.py
      arguments: -m poetry run pytest -s -ra --junitxml=junit/test-results.xml tests
